/**
 * author:yangbobin date:2015-11-19
 */
Ext.define('acesure.recovery.model.MountModel', {
	extend:'Ext.data.Model',
	fields:[ 
			{
				name:'deviceId',
				type:'string'
			 },
	         {
	        	name:'mountId',
	        	type:'string'
	         }, {
				name:'mountName',
				type:'string'
			}, {
				name:'mountDestDeviceId',
				type:'string'
			},
			{
				name:'mountDestDeviceIp',
				type:'string'
			}
			, 
			{
				name:'mountDestDeviceName',
				type:"string"
			}, {
				name:'mountType',
				type:"string"
			}, {
				name:'mountState',
				type:'string'
			},{
				name:'mountRemark',
				type:'string'
			}, {
				name:'diskCloneId',
				type:"string"
			}, {
				name:'sysType',
				type:'string'
			},{
				name:'snapSetId',
				type:'string'
			},
			{
				name:'parId',
				type:'string'
			},
			{
				name:'diskId',
				type:'string'
			},
			{
				name:'vmId',
				type:'string'
			}
			,
			{
				name:'mountPower',
				type:'string'
			}
			,
			{
				name:'mountLetter',
				type:'string'
			},
			{
				name:'vmimgName',
				type:'string'
			},
			{
				name:'vmimgCreateTime',
				type:'string'
			},
			{
				name:'storageName',
				type:'string'
			},
			{
				name:'storagePath',
				type:'string'
			},
			{
				name:'storageSymbol',
				type:'string'
			},
			{
				name:'vmimgDiskInfo',
				type:'string'
			},
			{
				name:'mountCreateTime',
				type:'string'
			},
			{
				name:'mountModifyTime',
				type:'string'
			},
			{
				name:'mountPower',
				type:'string'
			},
			{
				name:'sourceDeviceName',
				type:'string'
			},
			{
				name:'sourceDeviceIp',
				type:'string'
			},
			{
				name:'vmType',
				type:'string'
			},
			{
				name:'mountLabel',
				type:'string'
			},
			{
				name:'harddiskName',
				type:'string'
			},
			{
				name:'sourceDeviceId',
				type:'string'
			},
			{
				name:'storageState'
			},
			{
				name:'activeMountName'
			}
	]
});