Ext.define('acesure.recovery.model.SnapShotModel', {
	extend : 'Ext.data.Model',
	alias:"widget.SnapShotModel",
	fields : [ 
	          	{name:"deviceId",type:"string"},
	          	{name:"driverState",type:"string"},
	          	{name:"engineState",type:"string"},
	          	{name:"id",type:"string"},
	          	{name:"keepfullbackupEnable",type:"string"},
	          	{name:"keepfullbackupNum",type:"string"},
	            {name:"keepfullbackupType",type:"string"},
		        {name:"keepsnapEnable",type:"string"},
		        {name:"keepsnapNum",type:"string"},
		        {name:"keepsnapType",type:"string"},
		        {name:"limitedBackupSpeed",type:"string"},
		        {name:"limitedBackupSpeedKB",type:"string"},
		        {name:"limitedBackupTime",type:"string"},
		        {name:"online",type:"string"},
		        {name:"snapEnable",type:"string"},
		        {name:"snapIncreOldSnap",type:"string"},
		        {name:"snapIntervalType",type:"string"},
	          	{name:"snapIntervalValue",type:"string"},
	          	{name:"snapTimeRange",type:"string"},
	          	{name:"state",type:"string"},
	          	{name:"synchrEnable",type:"string"},
	          	{name:"synchrIntervalType",type:"string"},
	            {name:"synchrIntervalValue",type:"string"},
		        {name:"systemDesc",type:"string"},
		        {name:"targetPath",type:"string"},
		        {name:"targetType",type:"string"},
		        {name:"uuid",type:"string"},
		        {name:"workDesc",type:"string"},
		        {name:"workState",type:"string"}
		        ]
});